### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jqck3d** [Franckyi/IBE-Editor#11]
When editing an attribute of an item in the editor and pressing save, the game crashes.
This is for the new 1.16.2 Beta version BTW.

**Comment by Franckyi** [comment]
Fixed by ce34c2bc2649675d25fc3904399b8944c61cc1ad. Expect a fix to be released in a few minutes

**Comment by Franckyi** [comment]
@jqck3d Thanks for reporting the issue. A hotfix can be downloaded here: https://www.curseforge.com/minecraft/mc-mods/ibe-editor/files/3051835
