### ISSUE TITLE
Crash Report #2

### ISSUE THREAD

**Issue by jqck3d** [Franckyi/IBE-Editor#12]
Thank you for fixing the previous crash report, but I have found another. This one also is about applying attributes to an item.
If the attribute name is misspelled, the game crashes.

**Comment by Franckyi** [comment]
Fixed in ef113dd5df2c9d17b951c3a0e7d0f3000c078619. Stupid mistake on my end, sorry about that.

**Comment by Franckyi** [comment]
@jqck3d Thanks for reporting again, a fix has been released: https://www.curseforge.com/minecraft/mc-mods/ibe-editor/files/3052329
