### ISSUE TITLE
HideFlags incorrect value

### ISSUE THREAD

**Issue by DalekCraft2** [Franckyi/IBE-Editor#20]
Note that a bit of this is from memory:

A short while ago, I tried to use the HideFlags function in the item editor. I set all of the options to true, which would have hidden all of them and set the HideFlags value to 127. I checked with JEI Integration, and the value ended up being a much smaller value, which I can not recall. It may have been around or below 30.

**Comment by Franckyi** [comment]
Setting all the Hide Flags from the editor should set the value to 63, since I apparently forgot to add one of them (the flag that hides "Dyed" for leather armors). If it's really necessary I can add it now, otherwise it'll be added in the next version.

**Comment by Erisfiregamer1** [comment]
> Setting all the Hide Flags from the editor should set the value to 63, since I apparently forgot to add one of them (the flag that hides "Dyed" for leather armors). If it's really necessary I can add it now, otherwise it'll be added in the next version.

This is screwing me up badly, because I need the Dyed flag to not be true.

**Comment by Franckyi** [comment]
Fixed in version 1.2.7: https://www.curseforge.com/minecraft/mc-mods/ibe-editor/files/3397140
