### ISSUE TITLE
Could not find required mod: ibe editor requires {game adapter @ [2.0.0]}

### ISSUE THREAD

**Issue by maksmanus** [Franckyi/IBE-Editor#25]
Could not find required mod: ibe editor requires {game adapter @ [2.0.0]}

**Comment by maksmanus** [comment]
[07:39:33]
[main/INFO]: Загрузка для игры Minecraft 1.17.1
[07:39:34] [main/FATAL]: Произошла
критическая ошибка net.fabricmc.loader.discovery.ModResolutionException: Не
удалось найти
необходимый мод: ibeeditor требует {gameadapter @ [2.0.0]} at
net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198)
~[fabric-loader-0.11.6.jar:?]
at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832)
~[fabric-loader-0.11.6.jar:?]
at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195)
~[fabric-loader-0.11.6.jar:?]
at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185)
[fabric-loader-0.11.6.jar:?]
at net.fabricmc.loader.launch.knot.knot.knot.init(Knot.java:132)
[ткань-погрузчик-0.11.6.jar:?]
по адресу
net.fabricmc.loader.launch.knot.knotClient.main(KnotClient.java:28)
[ткань-погрузчик-0.11.6.jar:?]
Вызвано: net.fabricmc.loader.util.sat4j.specs.ContradictionException:
Создание пустого предложения ?
at
net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
~[fabric-loader-sat4j-2.3.5.4.jar:?]
at
net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
~[fabric-loader-sat4j-2.3.5.4.jar:?]
at
net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
~[fabric-loader-sat4j-2.3.5.4.jar:?]
at
net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
~[fabric-loader-sat4j-2.3.5.4.jar:?]
at
net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195)
~[fabric-loader-0.11.6.jar:?]
... Еще 5


чт, 26 авг. 2021 г. в 22:55, Franck V. ***@***.***>:

**Comment by Franckyi** [comment]
This sadly didn't give me any information. Can you send me a screenshot of the contents of your mods folder?
