### ISSUE TITLE
Crash when hovering over specific UI elements and pressing 'i'

### ISSUE THREAD

**Issue by starmun-0010** [Franckyi/IBE-Editor#35]
**Versions**

- MC: 1.16.5
- Forge: 36.2.2
- IBE: 2.0.2

**Description**

Pressing 'i' or the hotkey assigned to IBE while hovering over the recipe book button ![image](https://user-images.githubusercontent.com/5557278/131203729-b3cefdff-88d6-499f-931c-c0faa75e60e4.png) in your inventory crashes the game
It also crashes if you hover over an item in the JEI interface and press i.

**To  Reproduce**
1. Launch the game with IBE Editor and optionally JEI
2. Open your inventory by pressing E
3. Hover over the recipe book button in your inventory. (or hover over an item in JEI list)
4. Press the key assigned to IBE editor.
5. The game will crash.

**Logs**
[latest.log](https://github.com/Franckyi/IBE-Editor/files/7070041/latest.log)
[crash-2021-08-28_07.46.07-client.txt](https://github.com/Franckyi/IBE-Editor/files/7070042/crash-2021-08-28_07.46.07-client.txt)

**Comment by Franckyi** [comment]
Thanks for reporting the issue, the fix seem to be pretty straightforward. I'll fix it as soon as I can use a computer

**Comment by Franckyi** [comment]
Fixed in version 2.0.3
