### ISSUE TITLE
[BUG] Conflicts With Inventory Profiles Next

### ISSUE THREAD

**Issue by Phoupraw** [Franckyi/IBE-Editor#37]
When I used Inventory Profiles Next to sort a chest, the game crashed.
[crash-2021-08-30_18.59.30-client.txt](https://github.com/Franckyi/IBE-Editor/files/7076267/crash-2021-08-30_18.59.30-client.txt)

**Comment by Franckyi** [comment]
Thanks for reporting the issue, I'll look into it as soon as I get back home

**Comment by Franckyi** [comment]
Fixed in version 2.0.5
