### ISSUE TITLE
Item Editor – ability to edit custom tags

### ISSUE THREAD

**Issue by Felix14-v2** [Franckyi/IBE-Editor#41]
It would be useful to be able to view and edit custom tags that can be added to items (`/give @s minecraft:diamond{hello:world`}, for example)

**Comment by Franckyi** [comment]
If I understand correctly what you want, you can already do that in the NBT or SNBT Editor? (key N or R)

**Comment by Felix14-v2** [comment]
Yes, but it would be great for map makers to have a separate field on the main editor screen for this to easily change item tags.

**Comment by Franckyi** [comment]
Hmm the closest thing I'm thinking about would be to add shortcuts to switch between editors.
For example, you can start editing an item in the standard editor, then click on a button to switch to the NBT editor while keeping the changes you did in the standard editor. And you'd be able to go back to the standard editor from the NBT editor and keep the changes as well.
