### ISSUE TITLE
[BUG] Custom Display colors reset after opening edit UI and closing.

### ISSUE THREAD

**Issue by Erisfiregamer1** [Franckyi/IBE-Editor#44]
Every time I want to edit something, I have to go back and reset the color of the lore, or lose it.
***WHY?***

**Comment by Erisfiregamer1** [comment]
@Franckyi Did you fix this yet?
How to do:
- open custom lore item
- edit something abt item without opening display menu
- save item
- lose lore colors / spaces

**Comment by Franckyi** [comment]
Sorry, I thought I had already fixed it. I'll investigate it when I can find some time

**Comment by Franckyi** [comment]
@Erisfiregamer1 I unfortunately haven't been able to reproduce this issue. Can you send me the full NBT of the item you're trying to edit? (or a /give command)

**Comment by Erisfiregamer1** [comment]
This happens to any item I try to edit.

**Comment by Franckyi** [comment]
Can you send me screenshots of what you're doing exactly?

**Comment by Erisfiregamer1** [comment]
I already said the steps.
Open the item with already set colored lore.
Make an edit without opening the "display" section.
Close GUI. The colors are broken until you open Display and fix them.

**Comment by Erisfiregamer1** [comment]
Nevermind, seems a patch I was not aware of unintentionally fixed this.
