### ISSUE TITLE
game crash when trying to add enchanting

### ISSUE THREAD

**Issue by andrewgamingplayer5512** [Franckyi/IBE-Editor#48]
it crash
 when i try to add enchanting
[crash-2022-01-05_17.32.46-fml.txt](https://github.com/Franckyi/IBE-Editor/files/7813762/crash-2022-01-05_17.32.46-fml.txt)

**Comment by andrewgamingplayer5512** [comment]
in 1.18.1 (forgot to add)

**Comment by Franckyi** [comment]
The error in crash report you sent isn't related to IBE Editor. Can you send me your `latest.log` file instead? (after you reproduced the error)

**Comment by andrewgamingplayer5512** [comment]
[crash-2022-01-05_17.28.23-client.txt](https://github.com/Franckyi/IBE-Editor/files/7818731/crash-2022-01-05_17.28.23-client.txt)
here i click the wrong file

**Comment by Franckyi** [comment]
I'm suspecting some kind of mod incompatibility happening. I'll try to investigate what mod causes the issue.

**Comment by skyecodes** [comment]
Fixed in 2.0.9
