### ISSUE TITLE
Keybinding always resets itself every time I start up the game

### ISSUE THREAD

**Issue by mahilo3550** [Franckyi/IBE-Editor#5]
Minecraft: 1.12.2
Forge: 1.12.2-14.23.1.2610
IBE Editor: 1.12.2-1.0.0-alpha4

Only the keybinding for "Open GUI" always resets itself back to the "APPS" key (a key I don't really understand) between Alt and Ctrl buttons on the right side of the space bar. It could have something to do with this button's function, but I noticed another mod also resets only one of it's keybindings back to this key. I have to remap the controls every time I start Minecraft and I always assign "I" (capital i) for this mod's keybinding and just remove the others mods keybindings. The other mod is PlayerStorage and the keybinding is also "Open GUI" for this mod.

**Comment by Franckyi** [comment]
Thanks for reporting the issue. I'm currently working for a fix. Sorry for the inconvenience.
