### ISSUE TITLE
Item editor - Attribute values do not support inf

### ISSUE THREAD

**Issue by DogeisCut** [Franckyi/IBE-Editor#52]
![image](https://user-images.githubusercontent.com/23178844/161358137-36eb309c-1855-40ef-83b7-c42bd6f67231.png)

**Comment by n0789** [comment]
use "1.79769313486232E+308d" in NBT Editor and it will become "Infinity"

**Comment by DogeisCut** [comment]
I also just found out you can directly type "Infinity"
