### ISSUE TITLE
希望添加简体中文语言

### ISSUE THREAD

**Issue by hyplant** [Franckyi/IBE-Editor#58]
希望可以在模组中添加简体中文语言
目前我已经制作出了语言文件，可供参考，可能有些不完善的地方。
下面适用于2.1.2
{
  "ibeeditor": "IBE Editor汉化版",
  "ibeeditor.key.editor": "打开可视化NBT编辑器",
  "ibeeditor.key.nbt_editor": "打开通用的NBT编辑器",
  "ibeeditor.key.snbt_editor": "打开字符串NBT编辑器",
  "ibeeditor.key.bookmarks": "IBE剪贴板",
  "ibeeditor.gui.editor_title": "%s 编辑器",
  "ibeeditor.gui.settings": "调整设置",
  "ibeeditor.gui.switch_nbt_editor": "切换至NBT编辑器",
  "ibeeditor.gui.move_up": "上移",
  "ibeeditor.gui.move_down": "下移",
  "ibeeditor.gui.add": "添加子标签 %s",
  "ibeeditor.gui.remove": "删除该标签",
  "ibeeditor.gui.cut": "剪切",
  "ibeeditor.gui.copy": "复制",
  "ibeeditor.gui.paste": "粘贴到子标签",
  "ibeeditor.gui.collapse": "收起所有标签",
  "ibeeditor.gui.expand": "展开所有标签",
  "ibeeditor.gui.scroll_focused": "滚动至选中处",
  "ibeeditor.gui.zoom_reset": "重置界面尺寸",
  "ibeeditor.gui.zoom_out": "缩小界面",
  "ibeeditor.gui.zoom_in": "放大界面",
  "ibeeditor.gui.add_tag": "添加 %s 标签",
  "ibeeditor.gui.close_without_saving": "放弃并退出",
  "ibeeditor.gui.save": "保存并退出",
  "ibeeditor.gui.bold": "粗体",
  "ibeeditor.gui.italic": "斜体",
  "ibeeditor.gui.underline": "下划线",
  "ibeeditor.gui.strikethough": "删除线",
  "ibeeditor.gui.obfuscated": "乱码字",
  "ibeeditor.gui.reset_color": "重置色彩",
  "ibeeditor.gui.black": "黑色(000000)",
  "ibeeditor.gui.dark_blue": "深蓝(0000AA)",
  "ibeeditor.gui.dark_green": "深绿(00AA00)",
  "ibeeditor.gui.dark_aqua": "湖蓝(00AAAA)",
  "ibeeditor.gui.dark_red": "深红(AA0000)",
  "ibeeditor.gui.dark_purple": "紫色(AA00AA)",
  "ibeeditor.gui.gold": "金色(不祥，FFAA00)",
  "ibeeditor.gui.gray": "灰色(备注，AAAAAA)",
  "ibeeditor.gui.dark_gray": "深灰(555555)",
  "ibeeditor.gui.blue": "蓝色(效果附魔，5555FF)",
  "ibeeditor.gui.green": "黄绿(55FF55)",
  "ibeeditor.gui.aqua": "天蓝(稀有，55FFFF)",
  "ibeeditor.gui.red": "红色(负面效果，FF5555)",
  "ibeeditor.gui.light_purple": "品红(史诗，FF55FF)",
  "ibeeditor.gui.yellow": "黄色(少见，FFFF55)",
  "ibeeditor.gui.white": "白色(正常，FFFFFF)",
  "ibeeditor.gui.remove_custom_color": "移除所选颜色",
  "ibeeditor.gui.custom_color": "颜色[括号内可查看代码及用途]",
  "ibeeditor.gui.fix_errors": "输入内容有误，请修改后再保存",
  "ibeeditor.gui.reset": "重置",
  "ibeeditor.gui.search": "搜索:",
  "ibeeditor.gui.general": "通用",
  "ibeeditor.gui.display": "显示",
    "ibeeditor.gui.enchantment": "附魔",
  "ibeeditor.gui.enchantments": "附魔项",
  "ibeeditor.gui.attribute_modifiers": "物品栏用途",
  "ibeeditor.gui.modifier": "物品栏属性",
  "ibeeditor.gui.hide_flags": "隐藏标识",
  "ibeeditor.gui.item_id": "物品id",
  "ibeeditor.gui.choose": "选择预设%s",
  "ibeeditor.gui.count": "物品数量",
  "ibeeditor.gui.damage": "物品已用耐久",
  "ibeeditor.gui.custom_name": "物品显示名称",
  "ibeeditor.gui.lore": "备注 #%s",
  "ibeeditor.gui.lore_add": "添加备注",
  "ibeeditor.gui.level_add": "%s 等级",
  "ibeeditor.gui.attribute_name": "属性",
  "ibeeditor.gui.attribute": "物品属性",
  "ibeeditor.gui.slot": "可用栏位",
  "ibeeditor.gui.mainhand": "主手手持",
  "ibeeditor.gui.offhand": "副手手持",
  "ibeeditor.gui.feet": "穿在脚上时",
  "ibeeditor.gui.legs": "戴在腿部时",
  "ibeeditor.gui.chest": "穿在胸口时",
  "ibeeditor.gui.head": "戴在头上时",
  "ibeeditor.gui.all": "全部",
  "ibeeditor.gui.operation": "修饰方法: %s",
  "ibeeditor.gui.operation.0": "先在基值上加op1的和",
  "ibeeditor.gui.operation.1": "在上一步之后乘op2的和",
  "ibeeditor.gui.operation.2": "再上两步之后再乘上op3的积",
  "ibeeditor.gui.amount": "数量",
  "ibeeditor.gui.hide": "隐藏%s",
  "ibeeditor.gui.unbreakable": "无法破坏(无限耐久)",
  "ibeeditor.gui.can_destroy": "允许破坏方块",
  "ibeeditor.gui.can_place_on": "允许放置在上面",
  "ibeeditor.gui.other": "其它(放上鼠标来显示)",
  "ibeeditor.gui.dyed": "盔甲染色",
  "ibeeditor.gui.hide_other_tooltip.0": "隐藏项:",
  "ibeeditor.gui.hide_other_tooltip.1": "- 状态效果",
  "ibeeditor.gui.hide_other_tooltip.2": "- 盾牌图案",
  "ibeeditor.gui.hide_other_tooltip.3": "- 附魔书附魔",
  "ibeeditor.gui.hide_other_tooltip.4": "- 书本作者和\"原件\" / \"副本\"",
  "ibeeditor.gui.hide_other_tooltip.5": "- 爆炸数据",
  "ibeeditor.gui.hide_other_tooltip.6": "- 烟花数据",
  "ibeeditor.gui.hide_other_tooltip.7": "- 地图数据",
  "ibeeditor.gui.potion_effects": "药水效果",
  "ibeeditor.gui.default_potion": "原有效果",
  "ibeeditor.gui.potion_color": "药水颜色",
  "ibeeditor.gui.potion": "药水",
  "ibeeditor.gui.effect": "状态效果",
  "ibeeditor.gui.amplifier": "效果强度",
  "ibeeditor.gui.duration": "持续时长",
  "ibeeditor.gui.ambient": "信标效果(透明粒子和青色边框)",
  "ibeeditor.gui.show_particles": "显示粒子效果",
  "ibeeditor.gui.show_icon": "显示效果图标",
  "ibeeditor.gui.armor_color": "盔甲染色",
  "ibeeditor.gui.spawn_egg": "刷怪蛋",
  "ibeeditor.gui.block_state": "方块状态",
  "ibeeditor.gui.container": "容器",
  "ibeeditor.gui.lock_code": "容器密码",
  "ibeeditor.gui.health": "生命值",
  "ibeeditor.gui.always_show_name": "始终显示名字",
  "ibeeditor.gui.invulnerable": "无敌",
  "ibeeditor.gui.silent": "静音",
  "ibeeditor.gui.no_gravity": "无重力",
  "ibeeditor.gui.glowing": "高亮边框",
  "ibeeditor.gui.fire": "着火时长",
  "ibeeditor.gui.save_vault": "保存到数据库",
  "ibeeditor.gui.saved_vault.0": "%s将被保存到数据库",
  "ibeeditor.gui.saved_vault.1": "在应用修改之后保存到数据库",
  "ibeeditor.gui.saved_vault.2": "数据库保存操作2",
  "ibeeditor.gui.saved_vault.3": "再次按下按钮来取消",
  "ibeeditor.gui.edit": "编辑",
  "ibeeditor.gui.client": "对于其它客户端",
  "ibeeditor.gui.theme": "主题",
  "ibeeditor.gui.debug_mode": "调试模式",
  "ibeeditor.gui.selection_screen_max_items": " 页面中最大项目数",
  "ibeeditor.gui.common": "对于当前客户端",
  "ibeeditor.gui.permission_level": "权限等级",
  "ibeeditor.gui.creative_only": "仅允许创造模式",
  "ibeeditor.gui.reload_config": "重新加载配置文件",
  "ibeeditor.gui.level": "存档",
  "ibeeditor.gui.copy_command": "复制%s命令到剪贴板",
  "ibeeditor.gui.copy_command_alt": "复制命令",
  "ibeeditor.gui.command_copied.0": "%s命令将被复制到剪贴板",
  "ibeeditor.gui.command_copied.1": "在应用修改之后复制",
  "ibeeditor.gui.command_copied.2": "命令操作2",
  "ibeeditor.gui.command_copied.3": "再次按下按钮来取消",
  "ibeeditor.text.item": "物品",
  "ibeeditor.text.block": "方块",
  "ibeeditor.text.entity": "实体",
  "ibeeditor.text.vault": "数据库",
  "ibeeditor.message.error_permission_denied": "你没有权限使用%s编辑器。",
  "ibeeditor.message.error_server_mod": "IBE编辑器需要服务端模组来提供%s编辑功能。",
  "ibeeditor.message.success_update": "%s数据已保存。",
  "ibeeditor.message.no_target_found": "未发现可供编辑的%s。",
  "ibeeditor.message.error_generic": "出现错误，详见日志文件。你可以把错误反馈给模组作者。",
  "ibeeditor.message.not_implemented": "暂时不支持编辑%s，它可能会在日后被加入。",
  "ibeeditor.message.saved_vault": "%s已保存到数据库。",
  "ibeeditor.message.not_saved_vault": "%s已存在于数据库中。",
  "ibeeditor.message.copied_clipboard": "%s命令已复制到剪贴板。",
  "ibeeditor.message.no_block_data": "目标方块不是方块实体"
}

**Comment by neila-a** [comment]
我认为这个issues最好用英文写。
