### ISSUE TITLE
A little bug...

### ISSUE THREAD

**Issue by freerig** [Franckyi/IBE-Editor#60]
Hello, when I open the interface of IBE editor, I can quit it by presing esc, but I can also quite it by making a keyboard shortcut to open another interface, or by dying, and when I quit it by this way, I can no longer reopen the interface.

I think it's because the game believes it's allready open.
There had to be a command that actually closes the interface, like `/ibe close`

Thanks in advence

**Comment by skyecodes** [comment]
Will be fixed in version 2.2.0
