### ISSUE TITLE
SNBT format breaks strings

### ISSUE THREAD

**Issue by tryashtar** [Franckyi/IBE-Editor#62]
Hello, thanks for the great mod!

I noticed that when I click the "format text" button in the SNBT view, strings with spaces in them get changed to not have spaces anymore. And strings that contain characters like `{` get formatted, inserting whitespace and newlines. And this even persists after saving, which can break stuff.

**How to reproduce**
- Place a command block and put "say hello" in it
- Open SNBT editor
- Click format text
Result:
![image](https://user-images.githubusercontent.com/26075577/198213780-0072d359-43f5-4b38-8dcf-7ac99f9afea9.png)

[I guess this is the code that handles formatting?](https://github.com/Franckyi/IBE-Editor/blob/3b32de5148f3cb679b24e8571d670f7ea506c86d/common/src/main/java/com/github/franckyi/ibeeditor/client/screen/controller/SNBTEditorController.java#L34) I think vanilla has a builtin SNBT formatter that's a bit more robust (looks like yarn calls it `net.minecraft.nbt.visitor.NbtTextFormatter`), that might help make things a bit easier, if you don't mind the roundabout process of parsing to NBT and back.

**Comment by skyecodes** [comment]
Thank you for the report. I don't even know why I didn't think that it was going to break spaces in strings.

Thanks for telling me about the vanilla formatter btw, I didn't know it existed. I'll see if I can use it instead.

**Comment by skyecodes** [comment]
Fixed in version 2.2.1
