### ISSUE TITLE
IBE Editor don't work in 1.19.2

### ISSUE THREAD

**Issue by jucogjucogi** [Franckyi/IBE-Editor#68]
i can't open any of the editors. tried rebinding keys, settin controller binds - only vault works. cheating enabled, i'm in creative mode.
MC 1.19.2 with fabric. ask if need console logs or mod list.
edit: it works in 1.19.3, but not in 1.19.2

**Comment by skyecodes** [comment]
Please use the [1.19.2 version of the mod](https://modrinth.com/mod/ibe-editor/version/2.2.2+1.19-fabric) for Minecraft 1.19.2, the 1.19.3 version of the mod is only compatible with Minecraft 1.19.3.
