### ISSUE TITLE
Please update to 1.19.4

### ISSUE THREAD

**Issue by CCjun6** [Franckyi/IBE-Editor#76]
I really like this MOD and have been using it for a long time
Hope to update to 1.19.4 soon
If possible, I can provide sponsorship for you to develop

**Comment by arushenst** [comment]
Yes, I agree, please update to 1.19.4, in 1.19.4 they just fixed a bit of optimization so that some people will start updating to it

**Comment by skyecodes** [comment]
I am currently working on it. I still need to fix a bug in the SNBT editor.

**Comment by arushenst** [comment]
> I am currently working on it. I still need to fix a bug in the SNBT editor.

I thought you forgot

**Comment by skyecodes** [comment]
The mod has been updated to 1.19.4: https://github.com/skyecodes/IBE-Editor/releases/tag/2.2.2%2B1.19.4
