### ISSUE TITLE
Make IBE-Editor optional for client

### ISSUE THREAD

**Issue by Sgale952** [Franckyi/IBE-Editor#84]
On my server, only admins can use IBE-Editor. Ordinary players do not need this mod. Nevertheless, they download mod, since server does not let them in.

Is it possible to make IBE-Editor optional for client?

**Comment by skyecodes** [comment]
Fixed in [v2.2.4](https://github.com/skyecodes/IBE-Editor/releases/tag/2.2.4%2B1.20.2)
