### ISSUE TITLE
The block editing GUI should can open when the server is not install.

### ISSUE THREAD

**Issue by MC-luoluo** [Franckyi/IBE-Editor#85]
When the server is not installed, the client's block entity data page should be opened instead of being unable to open the GUI.

This is useful if you need to copy Banners or Player heads from other servers to your own server.

Used Google Translate, Chinese：

当服务端未安装时应该打开客户端获取到的方块实体数据界面，而不是根本打不开GUI。

这对于想从其他服务器把类似旗帜和玩家头颅之类的方块复制到自己的服务器十分有用。

**Comment by skyecodes** [comment]
Fixed in [v2.2.4](https://github.com/skyecodes/IBE-Editor/releases/tag/2.2.4%2B1.20.2)
