### ISSUE TITLE
error on 1.20.2 fabric when launching the game

### ISSUE THREAD

**Issue by Mrkq352** [Franckyi/IBE-Editor#87]
The mods Im using is only ibe editor and fabric api
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-11-06 21:24:09
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ibeeditor'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: io.netty.handler.codec.DecoderException: Not a compound tag: "id"
	at net.minecraft.class_2540.method_10798(class_2540.java:573)
	at com.github.franckyi.ibeeditor.client.Vault.lambda$loadFromFile$0(Vault.java:91)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at com.github.franckyi.ibeeditor.client.Vault.loadFromFile(Vault.java:91)
	at com.github.franckyi.ibeeditor.client.Vault.load(Vault.java:68)
	at com.github.franckyi.ibeeditor.client.ClientInit.setup(ClientInit.java:26)
	at com.github.franckyi.ibeeditor.fabric.FabricIBEEditorModClient.onInitializeClient(FabricIBEEditorModClient.java:21)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:466)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Biblioteka formantów czynności użytkownika:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:Biblioteka DLL interfejsu API klienta usługi DNS:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		IPSEng64.dll:IPS Script Engine DLL:17.2.12.33:Broadcom
		KERNEL32.DLL:Biblioteka DLL klienta Windows NT BASE API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Biblioteka DLL klienta Windows NT BASE API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Pomocnicza biblioteka DLL dla profilu zasilania:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Czas wykonania zdalnego wywoływania procedury:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Wspólna biblioteka DLL Powłoki systemu Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Współużytkowana biblioteka DLL klienta Windows USER API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Usługi Windows HTTP Services:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Biblioteka DLL 32-bitowej wersji usługi Windows Socket 2.0:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Biblioteka klienta zgodności aplikacji:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		bcrypt.dll:Biblioteka podstawowych elementów kryptograficznych systemu Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:Usługa klienta DHCP:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:Klient DHCPv6:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:Interfejs API trybu użytkownika funkcji FWP/IPSec:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna3843097132507844201.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Dostawca usługi:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Dostawca podkładek nazewnictwa poczty e-mail:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Router programu NCrypt w systemie Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:Biblioteka NT Layer DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT - dostawca MARTA:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Biblioteka DLL obiektów wydajności systemu Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:Dostawca obszaru nazw PNRP:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Biblioteka dodatkowych narzędzi powłoki:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		symamsi.dll:Symantec AMSI provider:15.7.12.41:Broadcom
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		win32u.dll:Win32u:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Interfejs API magazynu systemu Microsoft WinRT:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Biblioteka DLL typów systemu Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 577763576 bytes (550 MiB) / 1006632960 bytes (960 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-13700F
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 4060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2882
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3640
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 36190.29
	Virtual memory used (MB): 10946.04
	Swap memory total (MB): 3584.00
	Swap memory used (MB): 0.98
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 5.2.23
		architectury: Architectury 10.0.8
		auto-plant-crops: Auto Plant Crops 1.1.6
		autoelytra: Auto Elytra 2.1.0-1.20.2
		better-suggestions: Better Suggestions 1.2.0
		betterf3: BetterF3 8.0.1
		betterthirdperson: Better Third Person 1.9.0
		bobby: Bobby 5.0.2
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bridgingmod: Bridging Mod 2.1.1+1.20.2.fabric
		calcmod: CalcMod fabric-1.20.2-1.3.1
			clientarguments: clientarguments 1.6
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.0.6
		centered-crosshair: Centered Crosshair 1.0.3
		cherishedworlds: Cherished Worlds 7.0.0+1.20.2
		chesttracker: Chest Tracker 2.0.3+1.20.2
			whereisit: WhereIsIt 2.2.3+1.20.2
				jackfredlib: JackFredLib 0.5.16+1.20.2
					com_github_llamalad7_mixinextras: MixinExtras 0.2.0
					jackfredlib-base: JackFredLib: Base 1.1.5+1.20.2
					jackfredlib-colour: JackFredLib: Colour 1.0.3+1.20.2
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.0.6+1.20.2
					jackfredlib-gps: JackFredLib: GPS 1.0.3+1.20.2
					jackfredlib-lying: JackFredLib: Lying 0.4.6+1.20.2
					jackfredlib-toasts: JackFredLib: Toasts 1.0.4+1.20.2
		chunky: Chunky 1.3.92
		cloth-config: Cloth Config v12 12.0.109
			cloth-basic-math: cloth-basic-math 0.6.1
		colorfulhearts: Colorful Hearts 5.0.1
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		connected-doors: Connected Doors 1.2+1.20
		continuity: Continuity 3.0.0-beta.4+1.20.2
		controlling: Controlling For Fabric 13.0.1
		creativecore: CreativeCore 2.11.2
			net_minecraftforge_eventbus: eventbus 6.0.3
		dark-loading-screen: Dark Loading Screen 1.6.14
		detailab: Detail Armor Bar 2.6.3+1.20.2-fabric
		draggable_lists: Draggable Lists 1.0.2
		dynamic_fps: Dynamic FPS 3.2.1
		elementa: Elementa 614
		elytratime: Elytra Time 2.0.0
		enhancedbookwriting: EnhancedBookWriting 1.0.0+mc1.19.4
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		essential: Essential 14565+deploy-staging+g7d1e613e0b
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		essential-dependencies: Essential Dependencies 0
			universalcraft: UniversalCraft 318
		exordium: Exordium 1.2.1-mc1.20.2
		explosiveenhancement: Explosive Enhancement 1.2.1-1.20.x
		fabric-api: Fabric API 0.90.7+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.75+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.5+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.11+bff13c85a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.8+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.6+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.10+e3d2bf3fa0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.41+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.10+bb1ee60ea0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.23
		ferritecore: FerriteCore 6.0.0
		fullscreeno: fullscreeNO 1.0.0
		google-chat: GoogleChat 0.7.2
		here-be-no-dragons: Here be no Dragons! 1.0.0
		ibeeditor: IBE Editor 2.2.4
		idwtialsimmoedm: idwtialsimmoedm 0.2.0+1.20
		indium: Indium 1.0.27+mc1.20.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.7
		iris: Iris 1.6.10
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 12.1.3
		java: OpenJDK 64-Bit Server VM 17
		jumpfastuse: jumpfastuse 1.0
		languagereload: Language Reload 1.5.9+1.20.2
		lazydfu: LazyDFU 0.1.3
		leahs-immersive-thunder: Immersive Thunder 1.20.2+1.2.2
		libipn: libIPN 4.0.0
		libjf: LibJF 3.13.1
			libjf-base: LibJF Base 3.13.1
			libjf-config-commands: LibJF Config Commands 3.13.1
			libjf-config-core-v2: LibJF Config 3.13.1
			libjf-config-ui-tiny: LibJF Config UI: Tiny 3.13.1
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.13.1
			libjf-data-v0: LibJF Data 3.13.1
			libjf-mainhttp-v0: LibJF MainHTTP 3.13.1
			libjf-translate-v1: LibJF Translate 3.13.1
			libjf-unsafe-v0: LibJF Unsafe 3.13.1
			libjf-web-v1: LibJF Web 3.13.1
		lithium: Lithium 0.12.0
		loadingscreentips: Loading Screen Tips 1.3.2
			midnightlib: MidnightLib 1.5.0
		minecraft: Minecraft 1.20.2
		modernfix: ModernFix 5.8.1+mc1.20.2
		modmenu: Mod Menu 8.0.0
		nmuk: No More Useless Keys 1.1.0+mc1.20.1
		notenoughanimations: NotEnoughAnimations 1.6.4
		nvidium: Nvidium 0.2.0-beta
		org_jetbrains_annotations: annotations 13.0
		persistentgamemodeswitcher: PersistentGamemodeSwitcher 1.0.3.8
		postmortalparticles: Postmortal Particles 1.0.0-1.20.x
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.2-build.96
		remember-my-txt: Remember My Txt 1.0.1+MC1.20
		resourcify: Resourcify 1.2.1
		roughlyenoughitems: Roughly Enough Items 13.0.666
			error_notifier: Error Notifier 1.0.9
		searchables: Searchables 1.0.2
		seedmapper: SeedMapper 1.5.16
			betterconfig: BetterConfig 1.2.1
		servercountryflags: Server Country Flags 1.8.2
		shulkerboxtooltip: Shulker Box Tooltip 4.0.5+1.20.2
		skinlayers: 3d Skin Layers 1.5.6-mc1.20.2
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.2+mc1.20.2-build.113
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.2+fabric.bdaeb21
		status-effect-bars: Status Effect Bars 1.0.4
		timestamp_chat: Timestamp Chat 2.4.0+1.19.1
		tradeuses: Trade Uses 1.2.0
		uiutils: UI Utils 1.4.0
		viafabricplus: ViaFabricPlus 2.9.5
			net_lenni0451_reflect: Reflect 1.2.4
		vigilance: Vigilance 295
		visuality: Visuality 0.7.1+1.20
		vt_downloader: VTDownloader 2.1.0+1.20.2
		wurst: Wurst Client v7.38-MC1.20.2
		xaerominimap: Xaero's Minimap 23.8.2
		xaeroworldmap: Xaero's World Map 1.34.1
		xaerozoomout: XaeroZoomout 1.0.0+mc1.20.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20.2
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	JVM uptime in seconds: 17.284
	Launched Version: fabric-loader-0.14.23-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Locale: pl_PL
	CPU: <unknown>

**Comment by skyecodes** [comment]
Seems like an issue with the Vault file. Can you send the file located in `.minecraft/config/ibeeditor-vault.dat`?

**Comment by Mrkq352** [comment]
https://drive.google.com/file/d/1sZfbGrvBekyW8Y1MQHZl_CENDWLghSDP/view?usp=sharing

**Comment by skyecodes** [comment]
Fixed in [v2.2.5](https://github.com/skyecodes/IBE-Editor/releases/tag/2.2.5%2B1.20.2)
