### ISSUE TITLE
Adding potion effects doesn't work

### ISSUE THREAD

**Issue by Mrkq352** [Franckyi/IBE-Editor#88]
When i open the editor in game and add some potion effects to the item, the potion effects do not work (they show up in nbt but do not apply when using the item and they do not show up when hovering over the item)

**Comment by 12345hhh** [comment]
same issue

**Comment by 12345hhh** [comment]
![屏幕截图 2023-11-23 222354](https://github.com/skyecodes/IBE-Editor/assets/101722661/65258740-5fb1-4fa1-8a79-5c8a5495a774)
格式变了，左边是正确的格式，右边是模组生成的
mod version:v2.2.5     minecraft version:1.20.2

**Comment by skyecodes** [comment]
Fixed in [v2.2.6](https://github.com/skyecodes/IBE-Editor/releases/tag/2.2.6%2B1.20.2)
