### ISSUE TITLE
Allow using IBE only for OPs

### ISSUE THREAD

**Issue by medveed** [Franckyi/IBE-Editor#92]
i have a server running on 1.19.2 with forge 43.3.0. I installed this mod and now everyone can edit any items, event if they're in survival and dont have OP. So they can give themselves any block they want, of any quantity and with any enchantments. Could you make using IBE only allowed for OPs?

**Comment by skyecodes** [comment]
Have you tried setting the `permissionLevel` value to `4` in the `ibeeditor-common.json` config file on the server?

**Comment by medveed** [comment]
Thanks, that worked. Didn't know that it can be changed
