### ISSUE TITLE
Early version of IBE Editor 1.20.6

### ISSUE THREAD

**Issue by SayNooty** [Franckyi/IBE-Editor#99]
Is it possible to release an early version of Ibe Editor for MInecraft **1.20.6** neoforge/fabric (as beta)?

**Comment by skyecodes** [comment]
Yes early versions will be released when the mod takes shape. But for now it's still far from it. I'll keep updating on the progress in my Discord server.

**Comment by SayNooty** [comment]
Thanks! I'll be waiting! In the meantime, I'm going to join your discord server
